id: medcom.fhir.dk.notes
canonical: http://medcomfhir.dk/ig/notes
name: MedComNotes
title: DK MedCom Notes
description: The DK MedCom Notes IG
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: draft
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"

dependencies:
  ihe.iti.mhd: 4.2.3
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.core: dev
  medcom.fhir.dk.terminology: 2.0.1
  medcom.fhir.dk.xdsmetadata: dev
  medcom.fhir.dk.document: dev
  hl7.fhir.uv.extensions.r4: 5.2.0
  hl7.fhir.extensions.r5: 4.0.1

menu:
  Home: index.html
  Profiles: profiles.html
  Examples: examples.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters: 
  apply-version: false
  default-version: true
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true 