id: medcom.fhir.dk.notes
canonical: http://medcomfhir.dk/ig/notes
name: MedComNotes
title: DK MedCom Notes
description: The DK MedCom Notes IG
status: active # draft | active | retired | unknown
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: trial-use
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"

dependencies:
  ihe.iti.mhd: 4.2.3
  hl7.fhir.dk.core: 3.5.0
  medcom.fhir.dk.core: 4.0.0
  medcom.fhir.dk.terminology: 2.0.2
  medcom.fhir.dk.xdsmetadata: 1.0.1
  medcom.fhir.dk.document: 2.0.0
  hl7.fhir.extensions.r5: 4.0.1

menu:
  Home: index.html
  Profiles: profiles.html
  Examples: examples.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters: 
  apply-version: false
  default-version: true
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true 
  special-url:
    - urn:oid:1.2.208.176.1.1
    - urn:oid:1.2.208.176.1.4